#!/usr/bin/env python3
"""Generate the tap formula from the release bytes, without publishing it."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


def fail(message: str) -> "NoReturn":
    print(f"formula generation failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("dist", type=Path)
    parser.add_argument("--repository", default="thaodangspace/asana-cli")
    args = parser.parse_args()
    try:
        manifest = json.loads((args.dist / "release-manifest.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        # Snapshot validation runs before a final manifest exists.
        try:
            metadata = json.loads((args.dist / "metadata.json").read_text(encoding="utf-8"))
            manifest = {"tag": metadata["tag"], "version": metadata["version"]}
        except (OSError, KeyError, json.JSONDecodeError) as metadata_exc:
            fail(f"cannot read release metadata: {exc}; {metadata_exc}")

    tag = manifest.get("tag")
    version = manifest.get("version")
    if not isinstance(tag, str) or not isinstance(version, str):
        fail("release metadata has no tag and version")
    archives: dict[tuple[str, str], tuple[str, str]] = {}
    if "artifacts" in manifest:
        for artifact in manifest["artifacts"]:
            target = (artifact["goos"], artifact["goarch"])
            path = args.dist / artifact["name"]
            archives[target] = (artifact["name"], artifact["sha256"])
    else:
        for path in args.dist.glob("asana-cli_*_*.tar.gz"):
            parts = path.name.removesuffix(".tar.gz").rsplit("_", 2)
            if len(parts) == 3:
                archives[(parts[1], parts[2])] = (path.name, sha256(path))
    if set(archives) != {("darwin", "amd64"), ("darwin", "arm64"), ("linux", "amd64"), ("linux", "arm64")}:
        fail("formula requires exactly the four release archives")

    base = f"https://github.com/{args.repository}/releases/download/{tag}"
    def block(goos: str, goarch: str, linux: bool = False) -> str:
        name, checksum = archives[(goos, goarch)]
        condition = "Hardware::CPU.intel?" if goarch == "amd64" else "Hardware::CPU.arm?"
        if linux:
            condition += " && Hardware::CPU.is_64_bit?"
        return f'''    if {condition}\n      url "{base}/{name}"\n      sha256 "{checksum}"\n      def install\n        bin.install "asana-cli"\n      end\n    end'''

    formula = f'''# typed: false
# frozen_string_literal: true

# This file is generated by the release pipeline. DO NOT EDIT.
class AsanaCli < Formula
  desc "Asana CLI for agents and humans (JSON output by default)"
  homepage "https://github.com/{args.repository}"
  version "{version}"
  license "MIT"

  on_macos do
{block("darwin", "amd64")}
{block("darwin", "arm64")}
  end

  on_linux do
{block("linux", "amd64", True)}
{block("linux", "arm64", True)}
  end

  test do
    system "#{{bin}}/asana-cli", "--version"
  end
end
'''
    destination = args.dist / "homebrew" / "Formula" / "asana-cli.rb"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(formula, encoding="utf-8")
    print(destination)


if __name__ == "__main__":
    main()
